# PyMOL highlighting script -- generated by Stage 1 analyze_active_site.py
# 2Y9X: Agaricus bisporus mushroom tyrosinase + tropolone inhibitor

reinitialize
load C:/Users/Dell/Desktop/Hackathon_codex/data/structures/2Y9X.pdb, 2Y9X

hide everything
show cartoon, chain A
color grey80, chain A

select copper_site, chain A and resn CU
show spheres, copper_site
color orange, copper_site
set sphere_scale, 0.6, copper_site

select coord_his, chain A and resi 61+61+61+85+85+85+94+94+94+263+263+296+296+296+263+259+259+259
show sticks, coord_his
color cyan, coord_his
label coord_his and name CA, "%s%s" % (resn, resi)

select pocket, chain A and resi 58+60+61+62+81+82+83+84+85+86+89+90+91+93+94+95+97+98+244+255+256+257+259+260+262+263+279+280+281+282+283+284+285+286+287+288+291+292+293+295+296+297+299+400+401+410+2001
show surface, pocket
set transparency, 0.5, pocket
color lightblue, pocket

select tropolone, chain A and resn 0TR
show sticks, tropolone
color yellow, tropolone
set stick_radius, 0.25, tropolone

pseudoatom box_center, pos=[-9.686, -24.903, -40.217]
show spheres, box_center
color red, box_center
set sphere_scale, 0.3, box_center

zoom pocket
set ray_shadows, 0
bg_color black
